In [1]:
import numpy as np 

In [55]:
A = [[0, 1, 1],
     [0, 1, 2],
     [0, 1, 3],
     [0, 1, 4]]
X =  [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
X = np.matrix(X) +10
A = np.matrix(A)
A, X

(matrix([[0, 1, 1],
         [0, 1, 2],
         [0, 1, 3],
         [0, 1, 4]]),
 matrix([[11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]]))

In [57]:
display(A, X)
A@X

matrix([[0, 1, 1],
        [0, 1, 2],
        [0, 1, 3],
        [0, 1, 4]])

matrix([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]])

matrix([[31, 33, 35],
        [48, 51, 54],
        [65, 69, 73],
        [82, 87, 92]])

In [64]:
X[0,1]

12

In [75]:

Y = np.matrix([[0]*3]*4)
Y

matrix([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [79]:
#row = 0
#vec = 0
Y *= 0
for row in range(4):
    for col in range(3):
        aij = A[row, col]
        for vec in range(3):
            Y[row,vec] += aij * X[col, vec]
Y

matrix([[31, 33, 35],
        [48, 51, 54],
        [65, 69, 73],
        [82, 87, 92]])